version: "3.8"

services:
    api:
        build: .
        container_name: ir-system-be
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        environment:
            - ENVIRONMENT=development
        restart: unless-stopped
